title: Camila Pulido, PhD # your name (or website title) here
logo: "images/PortfolioCircularCrop.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  **Data Scientits | Neuroscientist**
  <br><br>
  Data Scientist with extensive experience in analytics for scientific research. 
  Led multifaceted research initiatives from conceptualization through execution, 
  demonstrating expertise in experimental design, data manipulation and interpretation. 
  Proficient in various data analysis tools and scripting languages.
  _*Authorized to work in the United States as a Green Card holder._
  <br><br>
  <a href="https://www.linkedin.com/in/camilapulido-phd/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-67QHGTVR06  # your Google Analytics tracking ID here
