title: Camila Pulido, PhD # your name (or website title) here
logo: "images/PortfolioCircularCrop.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Neuroscientist | Data Science
  <br><br>
  Result-driven Scientist with extensive experience in the field of neurobiology and research;
  specializing in data collection, analysis and interpretation, and project management. Proven track record of contributing to groundbreaking studies and collaborating 
  with global expert teams. Proficient in various data analysis tools and programming languages.
  <br><br>
  <a href="https://www.linkedin.com/in/camilapulido-phd/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
